engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  scss-lint:
    enabled: true
    checks:
      VendorPrefix:
        enabled: false
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
ratings:
  paths:
  - src/**/*.html
  - src/**/*.js
  - src/**/*.scss
exclude_paths:
- src/registerServiceWorker.js
