---

language: node_js

node_js:
  - 8

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
