---

language: node_js

node_js:
  - "7"

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn build
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
