---

language: node_js

node_js:
  - 8

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  script:
    - yarn deploy

  on:
    branch: master
